# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_residentgender'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new_resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('F', 'Favorited'), ('A', 'Answered'), ('W', 'Accepted Answer'), ('E', 'Edited Article'), ('S', 'Also Commented'), ('NR', 'Created New Resident')], max_length=1),
        ),
    ]
