
postgres:
  image: postgres
  volumes:
    # If you are using boot2docker, postgres data has to live in the VM for now until #581 is fixed
    # for more info see here: https://github.com/boot2docker/boot2docker/issues/581
    - /data/careplus/postgres:/var/lib/postgresql/data

django:
  build: .
  command: python /careplus/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/careplus
  ports:
    - "8000:8000"
  links:
    - postgres

postgres:
  image: postgres
  volumes:
    # If you are using boot2docker, postgres data has to live in the VM for now until #581 is fixed
    # for more info see here: https://github.com/boot2docker/boot2docker/issues/581
    - /data/careplus/postgres:/var/lib/postgresql/data

django:
  build: .
  command: python /careplus/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/careplus
  ports:
    - "8000:8000"
  links:
    - postgres

