# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergencyContactFirstName', models.CharField(blank=True, default='John', max_length=50, null=True, verbose_name='First Name')),
                ('emergencyContactLastName', models.CharField(blank=True, default='Doe', max_length=50, null=True, verbose_name='Last Name')),
                ('emergnecyContactRelationship', models.CharField(blank=True, default='Child', max_length=50, null=True, verbose_name='Relationship')),
                ('emergencyContactPhoneNumber', models.CharField(blank=True, default='123-456-7890', max_length=12, null=True, verbose_name='Phone Number')),
            ],
            options={
                'ordering': ('-emergencyContactLastName',),
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residentFirstName', models.CharField(blank=True, default='John', max_length=50, null=True, verbose_name='First Name')),
                ('residentLastName', models.CharField(blank=True, default='Doe', max_length=50, null=True, verbose_name='Last Name')),
                ('residentSSN', models.CharField(blank=True, default='123456789', max_length=50, null=True, verbose_name='SSN')),
                ('residentDOB', models.CharField(blank=True, default='3/5/1980', max_length=50, null=True, verbose_name='DOB')),
                ('residentPrimaryPhysician', models.CharField(blank=True, default='Dr.John Kellenberger', max_length=50, null=True, verbose_name='Primary Physician')),
                ('location', models.CharField(blank=True, default='Room 8', max_length=50, null=True, verbose_name='Room Number')),
                ('medicareNumber', models.CharField(default='ZSY20193992', max_length=20, null=True, verbose_name='Medicare Number')),
                ('dnr_status', models.CharField(blank=True, default='ACTIVE|NOT ACTIVE', max_length=50, null=True, verbose_name='DNR Status')),
            ],
            options={
                'verbose_name': 'Resident',
                'ordering': ('-residentLastName',),
                'verbose_name_plural': 'Residents',
            },
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
    ]
