# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationcompletion',
            name='completionRx',
        ),
    ]
