# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicationSlug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slugs'),
        ),
    ]
