# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_remove_medicationcompletion_completionrx'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionRx',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medications.Medication'),
        ),
    ]
