# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20170714_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationtime',
            old_name='medication',
            new_name='timeMedication',
        ),
    ]
