# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medicationcompletion_completionrx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationcompletion',
            name='completionRx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication'),
        ),
    ]
