# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_auto_20170810_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationcompletion',
            name='completionDate',
            field=models.DateField(verbose_name='Date Given'),
        ),
    ]
