# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_auto_20170810_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationtime',
            name='timePRN',
            field=models.NullBooleanField(default=None, verbose_name='PRN?'),
        ),
    ]
