# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_medicationtime_timeprn'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionPRN',
            field=models.NullBooleanField(default=None, verbose_name='PRN'),
        ),
    ]
