# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_medicationtime_timerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationtime',
            name='timeRecord',
        ),
    ]
