# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_medicationcompletion_completionprn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationcompletion',
            name='completionPRN',
        ),
    ]
