# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_medicationtime_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medicationTimeSchedule3',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 3'),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicationTimeSchedule4',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 4'),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicationTimeSchedule5',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 5'),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicationTimeSchedule6',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 6'),
        ),
    ]
