# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0009_medicationtime_timedelivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationtime',
            name='timeRecord',
        ),
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionDue',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Due'),
        ),
    ]
