# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0010_auto_20170717_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicationTimeSchedule',
            field=models.TimeField(blank=True, null=True, verbose_name='Time 1'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationTimeSchedule2',
            field=models.TimeField(blank=True, null=True, verbose_name='Time 2'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationTimeSchedule3',
            field=models.TimeField(blank=True, null=True, verbose_name='Time 3'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationTimeSchedule4',
            field=models.TimeField(blank=True, null=True, verbose_name='Time 4'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationTimeSchedule5',
            field=models.TimeField(blank=True, null=True, verbose_name='Time 5'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationTimeSchedule6',
            field=models.TimeField(blank=True, null=True, verbose_name='Time 6'),
        ),
    ]
