# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0012_auto_20170717_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicationDistribution',
            field=models.CharField(blank=True, choices=[('0', 'PRN'), ('1', 'Every Day'), ('2', '2 times A Day'), ('3', '3 times a day'), ('4', '4 times a day'), ('5', '5 times a day'), ('6', '6 times a day')], max_length=50, null=True, verbose_name='Distribution'),
        ),
        migrations.AlterField(
            model_name='medicationtime',
            name='timeDue',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Time Due'),
        ),
    ]
