# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0013_auto_20170719_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationtime',
            old_name='medication',
            new_name='timeMedication',
        ),
    ]
