# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0015_auto_20170720_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationtime',
            name='timeDue',
            field=models.CharField(blank=True, max_length=20, verbose_name='Time Due'),
        ),
    ]
