# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0018_auto_20170721_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationcompletion',
            name='completionDue',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Time Due'),
        ),
        migrations.AlterField(
            model_name='medicationtime',
            name='timeDue',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Time Due'),
        ),
    ]
