# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 03:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicationName', models.CharField(blank=True, default='Medication', max_length=50, null=True, verbose_name='Medication Name')),
                ('medicationSlug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('medicationDosage', models.CharField(blank=True, default='e.g. 120 mg', max_length=50, null=True, verbose_name='Dosage')),
                ('medicationFrequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Frequency')),
                ('medicationDistribution', models.CharField(blank=True, choices=[('1', 'Every Day'), ('2', '2 times A Day'), ('3', '3 times a day'), ('4', '4 times a day'), ('5', '5 times a day'), ('6', '6 times a day'), ('7', '7 times a day'), ('8', '8 times a day'), ('9', '9 times a day'), ('10', '10 times a day'), ('11', '11 times a day'), ('12', '12 times a day'), ('24', '24 times a day')], max_length=50, null=True, verbose_name='Distribution')),
                ('medicationQuantity', models.IntegerField(blank=True, default='30', null=True, verbose_name='Quantity')),
                ('medicationType', models.CharField(blank=True, default='Narcotic', max_length=20, null=True, verbose_name='Drug Type')),
                ('medicationStatus', models.CharField(choices=[('False', 'Not Given'), ('True', 'Given')], default=False, max_length=10, verbose_name='Current Status')),
                ('medicationComment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Physician Order|Notes?')),
                ('medicationStartDate', models.DateField(default=datetime.datetime.now, verbose_name='Medication Start Date')),
                ('medicationTimeSchedule', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 1')),
                ('medicationTimeSchedule2', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 2')),
                ('medicationTimeSchedule3', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 3')),
                ('medicationTimeSchedule4', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 4')),
                ('medicationTimeSchedule5', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 5')),
                ('medicationTimeSchedule6', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 6')),
                ('medicationTimeSchedule7', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 7')),
                ('medicationTimeSchedule8', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 8')),
                ('medicationTimeSchedule9', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 9')),
                ('medicationTimeSchedule10', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 10')),
                ('medicationTimeSchedule11', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 11')),
                ('medicationTimeSchedule12', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time 12')),
                ('medicationTimeSchedule24', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='(13-24)')),
                ('medicationDiscontinuedStatus', models.CharField(blank=True, choices=[('Active', 'Active'), ('Discontinued', 'Discontinued')], default='Active', max_length=12, null=True, verbose_name='DC Status')),
                ('medicationDateTimeAdded', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medicationResident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident', verbose_name='Resident Name')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ('-medicationName',),
            },
        ),
        migrations.CreateModel(
            name='MedicationCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completionStatus', models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default='', verbose_name='Current Status')),
                ('completionTime', models.TimeField(auto_now_add=True, verbose_name='Time Given')),
                ('completionDate', models.DateField(auto_now_add=True, verbose_name='Date Given')),
                ('completionNote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('completionMedication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication')),
            ],
        ),
    ]
