# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicationStatus2',
            field=models.NullBooleanField(default=None, verbose_name='Current Status 2'),
        ),
    ]
