# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationtime',
            name='timeGivenStatus',
            field=models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], default=None, max_length=12, null=True, verbose_name='Given'),
        ),
    ]
