# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20170707_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicationStartDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Medication Start Date'),
        ),
    ]
