# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_auto_20170711_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMedicationFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStatus', models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Current Status')),
                ('timeStatus2', models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Current Status 2')),
                ('timeMissed', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medicaton Missed')),
                ('timeTime', models.TimeField(auto_now_add=True, verbose_name='Time Given')),
                ('timeDate', models.DateField(auto_now_add=True, verbose_name='Date Given')),
                ('timeNote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMedicationFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStatus', models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Current Status')),
                ('timeStatus2', models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Current Status 2')),
                ('timeMissed', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medicaton Missed')),
                ('timeTime', models.TimeField(auto_now_add=True, verbose_name='Time Given')),
                ('timeDate', models.DateField(auto_now_add=True, verbose_name='Date Given')),
                ('timeNote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMedicationOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStatus', models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Current Status')),
                ('timeStatus2', models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Current Status 2')),
                ('timeMissed', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medicaton Missed')),
                ('timeTime', models.TimeField(auto_now_add=True, verbose_name='Time Given')),
                ('timeDate', models.DateField(auto_now_add=True, verbose_name='Date Given')),
                ('timeNote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMedicationThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStatus', models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Current Status')),
                ('timeStatus2', models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Current Status 2')),
                ('timeMissed', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medicaton Missed')),
                ('timeTime', models.TimeField(auto_now_add=True, verbose_name='Time Given')),
                ('timeDate', models.DateField(auto_now_add=True, verbose_name='Date Given')),
                ('timeNote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMedicationTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStatus', models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Current Status')),
                ('timeStatus2', models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Current Status 2')),
                ('timeMissed', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medicaton Missed')),
                ('timeTime', models.TimeField(auto_now_add=True, verbose_name='Time Given')),
                ('timeDate', models.DateField(auto_now_add=True, verbose_name='Date Given')),
                ('timeNote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
            ],
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationStatus',
            field=models.CharField(choices=[('Null', 'Null'), ('False', 'Not Given'), ('True', 'Given')], default=False, max_length=10, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationStatus2',
            field=models.CharField(choices=[('Null', 'Null'), ('False', 'Not Given'), ('True', 'Given')], default=False, max_length=10, verbose_name='Current Status 2'),
        ),
        migrations.AddField(
            model_name='timemedicationtwo',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication'),
        ),
        migrations.AddField(
            model_name='timemedicationthree',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication'),
        ),
        migrations.AddField(
            model_name='timemedicationone',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication'),
        ),
        migrations.AddField(
            model_name='timemedicationfour',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication'),
        ),
        migrations.AddField(
            model_name='timemedicationfive',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication'),
        ),
    ]
