# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_auto_20170714_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationtime',
            old_name='timeMedication',
            new_name='medication',
        ),
    ]
