# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_auto_20170711_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemedicationone',
            name='timeStatus',
            field=models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='timemedicationone',
            name='timeStatus2',
            field=models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Given'),
        ),
    ]
