# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medication_medicationrecordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medicationMissed',
            field=models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medication Missed'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationDiscontinuedStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Discontinued', 'Discontinued')], default='Active', max_length=15, null=True, verbose_name='DC Status'),
        ),
    ]
