# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_auto_20170712_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemedicationone',
            name='timeDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='timemedicationone',
            name='timeTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Due'),
        ),
    ]
