# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_auto_20170708_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionMissed',
            field=models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medicaton Missed'),
        ),
    ]
