# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_remove_medicationtime_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationtime',
            name='timeRecord',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Time Record'),
        ),
    ]
