# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_auto_20170712_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemedicationfive',
            name='timeDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='timemedicationfive',
            name='timeStatus',
            field=models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='timemedicationfive',
            name='timeStatus2',
            field=models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Given'),
        ),
        migrations.AlterField(
            model_name='timemedicationfive',
            name='timeTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Due'),
        ),
        migrations.AlterField(
            model_name='timemedicationfour',
            name='timeDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='timemedicationfour',
            name='timeStatus',
            field=models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='timemedicationfour',
            name='timeStatus2',
            field=models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Given'),
        ),
        migrations.AlterField(
            model_name='timemedicationfour',
            name='timeTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Due'),
        ),
        migrations.AlterField(
            model_name='timemedicationthree',
            name='timeDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='timemedicationthree',
            name='timeStatus',
            field=models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='timemedicationthree',
            name='timeStatus2',
            field=models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Given'),
        ),
        migrations.AlterField(
            model_name='timemedicationthree',
            name='timeTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Due'),
        ),
        migrations.AlterField(
            model_name='timemedicationtwo',
            name='timeDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='timemedicationtwo',
            name='timeStatus',
            field=models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='timemedicationtwo',
            name='timeStatus2',
            field=models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Given'),
        ),
        migrations.AlterField(
            model_name='timemedicationtwo',
            name='timeTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Due'),
        ),
    ]
