# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_auto_20170717_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationtime',
            name='timeDelivered',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Delivered'),
        ),
    ]
