# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0011_auto_20170717_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='medicationStatus',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medicationStatus2',
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationComment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Physician Orders'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationType',
            field=models.CharField(blank=True, default='Need Options', max_length=20, null=True, verbose_name='Drug Type'),
        ),
    ]
