# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='residentProfile',
            field=models.FileField(blank=True, null=True, upload_to='resident_pictures/'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='location',
            field=models.CharField(blank=True, default='Room 8', max_length=50, null=True, verbose_name='Room'),
        ),
    ]
