# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_residentgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='residentStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='dnr_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True, verbose_name='DNR Status'),
        ),
    ]
