# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_auto_20170717_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='residentProfile',
            field=models.FileField(blank=True, null=True, upload_to='media/resident_pictures/'),
        ),
    ]
