# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicianOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderMedication', models.CharField(blank=True, default='John', max_length=50, null=True)),
                ('orderDetails', models.CharField(blank=True, default='Doe', max_length=50, null=True)),
                ('orderTime', models.CharField(blank=True, default='123456789', max_length=50, null=True)),
                ('orderPhysician', models.CharField(blank=True, default='3/5/1980', max_length=50, null=True)),
                ('orderDate', models.CharField(blank=True, default='Dr.John Kellenberger', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'PhysicianOrder',
                'verbose_name_plural': 'PhysicianOrders',
                'ordering': ('-orderDate',),
            },
        ),
    ]
